#!/usr/bin/env python3
"""
Batch unfollow users.

Usage:
    # From ID list
    python -m tools.batch_unfollow --ids 123,456,789

    # From file (one ID per line)
    python -m tools.batch_unfollow --file ids.txt

    # From enriched JSON (generated by enrich_users)
    python -m tools.batch_unfollow --json reports/twitter-archive/not_following_back-enriched-xxx.json

    # Dry run (preview without unfollowing)
    python -m tools.batch_unfollow --json file.json --dry-run
"""

import sys
import json
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import hashlib
import hmac
import urllib.parse
import secrets
import httpx

from utils.config import init_env, get_env

try:
    from rich.console import Console
    from rich.table import Table
    from rich.prompt import Confirm
    console = Console()
    RICH_AVAILABLE = True
except ImportError:
    RICH_AVAILABLE = False


def get_oauth_config():
    return {
        "api_key": get_env("X_API_KEY"),
        "api_secret": get_env("X_API_SECRET"),
        "access_token": get_env("X_ACCESS_TOKEN"),
        "access_secret": get_env("X_ACCESS_SECRET"),
    }


def generate_oauth_signature(method: str, url: str, params: dict, oauth_params: dict, config: dict) -> str:
    all_params = {**params, **oauth_params}
    sorted_params = "&".join(
        f"{urllib.parse.quote(k, safe='')}={urllib.parse.quote(v, safe='')}"
        for k, v in sorted(all_params.items())
    )

    base_string = "&".join([
        method.upper(),
        urllib.parse.quote(url, safe=""),
        urllib.parse.quote(sorted_params, safe=""),
    ])

    signing_key = f"{urllib.parse.quote(config['api_secret'], safe='')}&{urllib.parse.quote(config['access_secret'], safe='')}"

    signature = hmac.new(
        signing_key.encode(),
        base_string.encode(),
        hashlib.sha1
    ).digest()

    import base64
    return base64.b64encode(signature).decode()


def build_oauth_header(method: str, url: str, params: dict = None) -> str:
    config = get_oauth_config()
    params = params or {}

    oauth_params = {
        "oauth_consumer_key": config["api_key"],
        "oauth_token": config["access_token"],
        "oauth_signature_method": "HMAC-SHA1",
        "oauth_timestamp": str(int(time.time())),
        "oauth_nonce": secrets.token_hex(16),
        "oauth_version": "1.0",
    }

    oauth_params["oauth_signature"] = generate_oauth_signature(method, url, params, oauth_params, config)

    header_params = ", ".join(
        f'{urllib.parse.quote(k, safe="")}="{urllib.parse.quote(v, safe="")}"'
        for k, v in sorted(oauth_params.items())
    )

    return f"OAuth {header_params}"


def get_my_user_id() -> str:
    """Get the authenticated user's ID."""
    url = "https://api.twitter.com/2/users/me"
    auth_header = build_oauth_header("GET", url)
    response = httpx.get(url, headers={"Authorization": auth_header}, timeout=30)
    data = response.json()
    if "data" in data:
        return data["data"]["id"]
    raise Exception(f"Failed to get user ID: {data}")


def unfollow_user(my_user_id: str, target_user_id: str) -> tuple[bool, str]:
    """Unfollow a user. Returns (success, message)."""
    url = f"https://api.twitter.com/2/users/{my_user_id}/following/{target_user_id}"
    auth_header = build_oauth_header("DELETE", url)

    try:
        response = httpx.delete(url, headers={"Authorization": auth_header}, timeout=30)
        data = response.json()

        if response.status_code == 200:
            return True, "OK"
        elif response.status_code == 429:
            return False, "RATE_LIMITED"
        else:
            return False, data.get("detail", str(data))
    except Exception as e:
        return False, str(e)


def load_ids_from_json(filepath: str) -> list[dict]:
    """Load user data from enriched JSON file."""
    with open(filepath, "r") as f:
        return json.load(f)


def load_ids_from_file(filepath: str) -> list[str]:
    """Load IDs from text file (one per line)."""
    with open(filepath, "r") as f:
        return [line.strip() for line in f if line.strip()]


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Batch unfollow users")
    parser.add_argument("--ids", help="Comma-separated user IDs")
    parser.add_argument("--file", help="File with user IDs (one per line)")
    parser.add_argument("--json", help="Enriched JSON file from enrich_users")
    parser.add_argument("--dry-run", action="store_true", help="Preview without unfollowing")
    parser.add_argument("--delay", type=float, default=2.0, help="Delay between unfollows (seconds)")
    parser.add_argument("--yes", "-y", action="store_true", help="Skip confirmation")
    args = parser.parse_args()

    if not any([args.ids, args.file, args.json]):
        parser.print_help()
        print("\n❌ Must provide --ids, --file, or --json")
        sys.exit(1)

    init_env()

    config = get_oauth_config()
    if not all(config.values()):
        print("❌ OAuth 1.0a credentials required")
        sys.exit(1)

    # Load users
    users = []
    if args.ids:
        for uid in args.ids.split(","):
            users.append({"user_id": uid.strip(), "username": "unknown"})
    elif args.file:
        for uid in load_ids_from_file(args.file):
            users.append({"user_id": uid, "username": "unknown"})
    elif args.json:
        users = load_ids_from_json(args.json)

    # Filter out NOT_FOUND users
    valid_users = [u for u in users if u.get("username") != "NOT_FOUND"]

    print("=" * 60)
    print("🗑️  Batch Unfollow")
    print("=" * 60)
    print(f"\n📋 Total users to unfollow: {len(valid_users)}")

    if args.dry_run:
        print("\n⚠️  DRY RUN MODE - No actual unfollows will happen\n")

    # Show preview
    if RICH_AVAILABLE:
        table = Table(title="Users to Unfollow")
        table.add_column("#", style="dim")
        table.add_column("Username")
        table.add_column("User ID")
        table.add_column("Followers", justify="right")

        for i, user in enumerate(valid_users[:20], 1):
            table.add_row(
                str(i),
                f"@{user.get('username', 'N/A')}",
                user.get("user_id", ""),
                f"{user.get('followers_count', 0):,}"
            )

        if len(valid_users) > 20:
            table.add_row("...", f"... and {len(valid_users) - 20} more", "", "")

        console.print(table)
    else:
        print("\nPreview (first 10):")
        for i, user in enumerate(valid_users[:10], 1):
            print(f"  {i}. @{user.get('username', 'N/A')} (ID: {user.get('user_id')})")
        if len(valid_users) > 10:
            print(f"  ... and {len(valid_users) - 10} more")

    # Confirmation
    if not args.dry_run and not args.yes:
        if RICH_AVAILABLE:
            if not Confirm.ask(f"\n⚠️  Proceed with unfollowing {len(valid_users)} users?"):
                print("Cancelled.")
                sys.exit(0)
        else:
            confirm = input(f"\n⚠️  Proceed with unfollowing {len(valid_users)} users? (y/N): ")
            if confirm.lower() != "y":
                print("Cancelled.")
                sys.exit(0)

    if args.dry_run:
        print("\n✅ Dry run complete. No users were unfollowed.")
        sys.exit(0)

    # Get my user ID
    print("\n🔑 Getting authenticated user ID...")
    my_user_id = get_my_user_id()
    print(f"   My ID: {my_user_id}")

    # Execute unfollows
    print(f"\n🚀 Starting unfollow process (delay: {args.delay}s between each)...\n")

    success_count = 0
    fail_count = 0
    rate_limited = False

    for i, user in enumerate(valid_users, 1):
        uid = user.get("user_id")
        username = user.get("username", "unknown")

        print(f"[{i}/{len(valid_users)}] @{username} (ID: {uid})... ", end="", flush=True)

        success, msg = unfollow_user(my_user_id, uid)

        if success:
            print("✅")
            success_count += 1
        elif msg == "RATE_LIMITED":
            print("⏳ Rate limited! Waiting 60s...")
            time.sleep(60)
            # Retry
            success, msg = unfollow_user(my_user_id, uid)
            if success:
                print(f"  ✅ Retry succeeded")
                success_count += 1
            else:
                print(f"  ❌ Retry failed: {msg}")
                fail_count += 1
        else:
            print(f"❌ {msg}")
            fail_count += 1

        # Delay between unfollows
        if i < len(valid_users):
            time.sleep(args.delay)

    # Summary
    print("\n" + "=" * 60)
    print("📊 Summary")
    print("=" * 60)
    print(f"   ✅ Unfollowed: {success_count}")
    print(f"   ❌ Failed: {fail_count}")
    print(f"   📋 Total: {len(valid_users)}")


if __name__ == "__main__":
    main()
